### ISSUE TITLE
Disbott V3.0

### ISSUE THREAD

**Issue by 80cmdude** [paguco/disbott#24]
So here we are 3 people that now know (kinda) how to code. However we are all coding in different (but similar) languages.

So for Disbott V3 what language are we going to choose to rewrite it in.

Or alternativily what is the new project to do.. Something MVC related maybe?

**Comment by tomopagu** [comment]
https://github.com/RogueException/Discord.Net (http://rtd.discord.foxbot.me/en/docs-dev/index.html) is the main C# one. Your Java choices are https://github.com/DV8FromTheWorld/JDA/ & https://github.com/austinv11/Discord4J. I'd personally prefer the C# one.

We could integrate this with an MVC since rather than having nedb as a local database we'd use an actual mysql/nosql table for memory. Though it's easier if we come up with something else for an MVC. I guess for the other idea we could do website in C# and then @Thatdwarf can do an android app with Java since that's the main language there if we can think of an app/website/project.

**Comment by 80cmdude** [comment]
That's like the most well documented thing i've ever seen in my life. (The c#). No one ever documents anything. That doesn't seem to bad.

**Comment by tomopagu** [comment]
Am locking the conversation here, instead please use #25 for conversation on this.

**Comment by tomopagu** [comment]
Done with the pull request, everything else V3 related should be in trello or in the milestone
